spring:
  application:
    name: exec-dubbo-api
server:
  port: 9092
dubbo:
  application:
    name: exec-dubbo-api
  registry:
    # zookeeper://192.168.43.175:12181?backup=192.168.43.175:12182,192.168.43.175:12183
    address: zookeeper://192.168.43.175:12181
  consumer:
    timeout: 5000
