server:
  port: 8021
spring:
  application:
    name: exec-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 虚拟host 可以不设置,使用server默认host
    #virtual-host: /
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    publisher-confirms: true
