spring:
  application:
    name: exec-dubbo-provider
server:
  port: 9091
dubbo:
  application:
    name: exec-dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.43.175:12181
