test:
  uri: lb://exec-sub-appweb

server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: exec-sub-appweb
        uri: ${test.uri}
        predicates:
        - Path=/app/**
        filters:
          - StripPrefix=1  #表示在转发时去掉userapi
          - name: Hystrix
            args:
              name: myfallbackcmd
              fallbackUri: forward:/app/fallback

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
